In [2]:
!pip install pandas
!pip install numpy

Collecting pandas
  Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sbadiger\tfenv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sbadiger\tfenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sbadiger\tfenv\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\sbadiger\tfenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.9 MB 4.8 MB/s eta 0:00:02
   ------ --------------------------------- 1.6/9.9 MB 4.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 3.3 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 3.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/9.9 MB 2.8 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.9 MB 2.8 MB/s eta 0:00:03
   ---------------- ----------------------- 4.2/9.9 MB 2.8 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.9 MB 2.8 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/9.9 MB 2.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.9 MB 2.9 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.9 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.9 MB 3.0 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.9 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/9.9 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 3.0 MB/s  0:00:03
Installing collected packages: pandas
Successfully installed pandas-3.0.2
Requirement already satisfied: numpy in C:\Users\sbadiger\tfenv\Lib\site-packages (2.4.4)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
import tensorflow as tf
print(tf.__version__)

RuntimeError: ('\nCould not import original test/binary location, import paths tried: [\'litert.python._pywrap_tensorflow_lite_metrics_wrapper\', \'tensorflow.lite.python._pywrap_tensorflow_lite_metrics_wrapper\', \'tensorflow._pywrap_tensorflow_lite_metrics_wrapper\', \'tensorflow.python._pywrap_tensorflow_lite_metrics_wrapper\']. \nPrevious exceptions: ["No module named \'litert\'", \'DLL load failed while importing _pywrap_tensorflow_lite_metrics_wrapper: The specified module could not be found.\', "No module named \'tensorflow._pywrap_tensorflow_lite_metrics_wrapper\'", "No module named \'tensorflow.python._pywrap_tensorflow_lite_metrics_wrapper\'"]', ModuleNotFoundError("No module named 'tensorflow.python._pywrap_tensorflow_lite_metrics_wrapper'"))

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.layers import Dense , Input

#### Linear Regression

In [ ]:
### Clean the data
rdata = pd.read_csv(r'C:\Users\sbadiger\AI_Practice_Excelr\datasets\insurance.csv')
rdata.head()

In [ ]:
rdata.info()

In [14]:
### for object data standardise and for other data standardise the data.
from sklearn.preprocessing import LabelEncoder, StandardScaler
enc = LabelEncoder()
scaler = StandardScaler()
for column in rdata.columns:
    if rdata[column].dtype == 'object':
        rdata[column] = enc.fit_transform(rdata[column])
    else:
        rdata[column] = scaler.fit_transform(rdata[[column]])
rdata.head()

        age  sex       bmi  children  smoker  region   charges
0 -1.438764    0 -0.453320 -0.908614       1       3  0.298584
1 -1.509965    1  0.509621 -0.078767       0       2 -0.953689
2 -0.797954    1  0.383307  1.580926       0       2 -0.728675
3 -0.441948    1 -1.305531 -0.908614       0       1  0.719843
4 -0.513149    1 -0.292556 -0.908614       0       1 -0.776802

In [15]:
### Split the data
X = rdata.drop('charges',axis=1)
Y = rdata['charges']

In [16]:
X.head()

        age  sex       bmi  children  smoker  region
0 -1.438764    0 -0.453320 -0.908614       1       3
1 -1.509965    1  0.509621 -0.078767       0       2
2 -0.797954    1  0.383307  1.580926       0       2
3 -0.441948    1 -1.305531 -0.908614       0       1
4 -0.513149    1 -0.292556 -0.908614       0       1

In [18]:
Y.head()

0    0.298584
1   -0.953689
2   -0.728675
3    0.719843
4   -0.776802
Name: charges, dtype: float64

In [22]:
X.shape

(1338, 6)

In [23]:
### Build the model and adding layers
### No of neurons is based on no of features - 6neurons and 8 hidden layer
model = Sequential(
   [Input(shape=(X.shape[1],)),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='linear')]
)

NameError: name 'Sequential' is not defined